name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0
        with:
          heroku_email: '${{ secrets.HEROKU_EMAIL }}'
          heroku_api_key: '${{ secrets.HEROKU_API_KEY }}'
          heroku_app_name: '${{ secrets.HEROKU_APP_NAME }}'
          useforce: true
          dynamicFiles: true
          env_file: sample.config.env
          buildpacks: >-
            ['https://github.com/heroku/heroku-buildpack-python','https://github.com/rking32/heroku-buildpack-google-chrome','https://github.com/rking32/heroku-buildpack-chromedriver','https://github.com/opendoor-labs/heroku-buildpack-p7zip','https://github.com/chrismytton/heroku-buildpack-jq.git','https://github.com/heroku/heroku-buildpack-apt.git','https://github.com/HasibulKabir/heroku-buildpack-rarlab.git','https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git']
